title: "DSCI320-Project"
author: "KBN"
description: "DSCI320-Project"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu
navigation:
  - {file: "index.md", title: "M2: Intro"}
  - {file: "02_about_the_data.md", title: "M2: Data"}
  - {file: "03_eda.md", title: "M2: EDA"}
  - {file: "04_research_q_and_task_analysis.md", title: "M2: Research & Tasks"}
  - {file: "05_preliminary_sketches.md", title: "M2: Prelim Sketches"}
  - {file: "06_sustainability_focus_viz.html", title: "M3: Sustainability Viz"}
  - {file: "07_planting_focus_viz.html", title: "M3: Planting Viz"}
  - {file: "08_picnic_focus_viz.html", title: "M3: Picnic Viz"}
  - {file: "references.md", title: "References"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
